### PR TITLE
Feature: Allow command functions to return Vue Components

### LINKED ISSUE #5: Feature: Allow commands to return components
To imitate interactivity, like:

https://askubuntu.com/questions/1705/how-can-i-create-a-select-menu-in-a-shell-script

Returning a component as STDOUT would be appropriate. **Problem**: It may not be simple anymore to return just a string, which makes the API much more complex.

### PR DESCRIPTION
**Pull request by krmax44**
## Demos

`yarn serve` and enter `loading`, `nano` or `klieh`.

## To Do

- [x] Command functions can return Vue Components
- [x] It is waited until `this.$done()` is called
- [x] Hide cursor when command is running
- [x] Helper functions/components/computed variables
  - [x] `this.$goFullscreen()` - to create commands like `nano`
  - [x] `this.$executeCommand(command: string)` - to call subsequent commands
  - [x] `this.$running` - computed boolean property indicating status (`false` after calling `this.$done()`)
- [x] Add docs
- [x] Requires #80 to be merged first.

Closes #5

### CODE REVIEW

**Comment by ndabAP** [comment]
Hey, could you write quickly what `<vue-command-input>` does?

**Comment by krmax44** [comment]
@ndabAP it doesn't exist yet, but I'd imagined it would be a simple styled input field. Then again a normal `<input>` with the base style applied is probably fine anyway. So not really needed, since most users that would take advantage of it would probably need to tweak it anyhow.

**Comment by krmax44** [comment]
Here's a usage example illustrating what's possible with this feature: https://klieh.space ([source](https://gitlab.com/klieh/klieh.space))

Commands that couldn't be created before: [`36c3`](https://gitlab.com/klieh/klieh.space/blob/master/src/commands/36c3.vue), [`home`](https://gitlab.com/klieh/klieh.space/blob/master/src/commands/home.vue)
Commands that were possible before but can now be written easier: [`export`](https://gitlab.com/klieh/klieh.space/blob/master/src/commands/export.vue), [`stripper`](https://gitlab.com/klieh/klieh.space/blob/master/src/commands/stripper.vue)

**Comment by ndabAP** [comment]
Absolutely impressive work! Thanks a lot! I started checking it.

**Comment by ndabAP** [comment]
Would you mind continue working here: https://github.com/ndabAP/vue-command/pull/104

**Comment by krmax44** [comment]
Sure! Are you by any chance at 36c3? :)

**Comment by ndabAP** [comment]
@krmax44 how do you mean that?

**Comment by krmax44** [comment]
Whether you happen to be at this year's CCC Congress https://events.ccc.de/congress/2019/wiki/index.php/Main_Page

**Comment by ndabAP** [comment]
@krmax44 ah, nice you asked. But don't plan to go there :)

**Pull request closed without merging**
