### PR TITLE
Add async command support

### LINKED ISSUE #28: Add Promise support
It would be great if a command could return a `Promise` - this would allow for asynchronous commands.  For example:

```
data: () => ({
  commands: {
   'my-async-command': ({ _ }) => {
      return new Promise(resolve => {
        setTimeout(() => {
          resolve(`You typed: "${_.join(' ')}"`);
        }, 2000);
      });
    },
  },
})
```

### PR DESCRIPTION
**Pull request by nfriend**
Here's one idea of how to add asynchronous command support.  Let me know what you think!

Closes #28

### CODE REVIEW

**Comment by nfriend** [comment]
By the way, this library is really nicely organized!  Great work!

**Comment by ndabAP** [comment]
Thank you so much for that! Also, your commits look very good to me. Does the command still work without a promise?

**Comment by nfriend** [comment]
This change is backwards compatible - no breaking change necessary.  The commands can now return either a regular `String` (like they did before) or a Promise that resolves to a `String`.

**Comment by ndabAP** [comment]
Awesome :)

**Pull request merged**
