### PR TITLE
Fix: Parsed options

### LINKED ISSUE #176: Bug: Spaces in options
Hi,

In earlier versions I could input options like this one:

`exec Do-Stuff --stuff "great stuff"`

this does not check out currently.
Having `yargs` in earlier versions did this really well.

For reproduction, use the demos `reverse` command like this:
`reverse "text with space"`

### PR DESCRIPTION
**Pull request by ndabAP**
Closes #176.

### CODE REVIEW

**Comment by ndabAP** [comment]
@kdlslyv I'm finished with some refactoring and would be happy a to get a final feedback from you.

**Comment by kdlslyv** [comment]
@ndabAP hi, sorry for the late reply
Looks very clean and certainly does the job 👍 

Let's not forget to add the `echo` command to the `help` command! 
Thank you again for offering the opportunity to do PRs and dealing with mine despite the lead times involved.

**Comment by ndabAP** [comment]
>Let's not forget to add the echo command to the help command!

Ah, good catch! I added it.

>Thank you again for offering the opportunity to do PRs and dealing with mine despite the lead times involved.

You're welcome. Thanks a lot for your effort.

**Pull request merged**
