### PR TITLE
intro: change from mustaches to v-html

### PR DESCRIPTION
**Pull request by iquidus**

### CODE REVIEW

**Comment by krmax44** [comment]
What about using a named slot like in#112? @iquidus @ndabAP

**Comment by ndabAP** [comment]
I'd also say it slots are a good solution to make this possible. @iquidus what concrete problem should `v-html` solve you have?

**Comment by iquidus** [comment]
Was in a hurry with this, went for v-html as I wanted a more complex intro than a one line string. (e.g mimic the intro seen on ssh login into a ubuntu server), figured v-html was the least intrusive change to make this happen. Behaves consistently with commands (allows html tags). Slots would be a more robust/ideal approach.

**Comment by ndabAP** [comment]
Closing since no activity.

**Pull request closed without merging**
