### PR TITLE
Feature: Make built-in commands more explicit

### LINKED ISSUE #78: Feature (breaking change): Consider passing dedicated arguments for built-in commands
The API gets bloated and unclear if the whole `$data` object is passed for `built-in` commands. It can also lead to unexpected behavior since the user is in full control. Therefore, it should be considered to pass only certain attributes, e. g. only `executed`.

### PR DESCRIPTION
**Pull request by ndabAP**
The instance now accepts the following internally used properties:

- `executed`, non-empty executed commands
- `history`, all executed commands
- `current`, current input

Providing these properties makes it possible to control the behavior on a lower level. For example, the Bash command `clear` could be implemented like this:

```js
const clear = () => {
  this.history = []
  // Wait for DOM
  await this.$nextTick()
  this.history = ['']

  this.executed.clear()
}
```

Closes #78.

### CODE REVIEW

**Comment by krmax44** [comment]
I find the distinction between commands and built-in commands a little strange. Why is there a difference? Also, I feel like this snippet is very overwhelming for newcomers:

```js
this.history = [] // ok, makes sense
// Wait for DOM
await this.$nextTick() // why do I have to wait?
this.history = [''] // why do I need to set it to an empty string?!

this.executed.clear() // what does this do? why can I do this.executed.clear() but not this.history.clear()?! 
```

**Comment by ndabAP** [comment]
@krmax44 I understand your points. Built in commands are inspired by Bash built in commands:

>Bash builtin commands (also known as "internal command") are part of the shell itself. Each builtin command is executed directly in the shell itself, instead of an external programme which the bash would load and run

For example, `clear` is a built in command. I want to provide a more native possibility to interact with the terminal and therefore, give access to internal processes. The idea of sharing a variable came from Vuetify: At the [data tables](https://vuetifyjs.com/en/components/data-tables) component, one can pass `page` with `sync` modifier. Vuetify mutates the page but at the same time the user can also modify it.

**Comment by krmax44** [comment]
@ndapAP These are all things obvious to us because we know the code behind it, it's just off-putting from a beginner perspective.

**Comment by ndabAP** [comment]
@krmax44 I understand, the main idea was to force more effort to indicate that dealing with built ins leads to more responsibility. Two programmers working the terminal could split and only one needs deeper knowledge how the library works.

**Comment by ndabAP** [comment]
Closed because of https://github.com/ndabAP/vue-command/pull/144.

**Pull request closed without merging**
