### PR TITLE
Feature: Allow command functions to return Vue.js Components

### LINKED ISSUE #5: Feature: Allow commands to return components
To imitate interactivity, like:

https://askubuntu.com/questions/1705/how-can-i-create-a-select-menu-in-a-shell-script

Returning a component as STDOUT would be appropriate. **Problem**: It may not be simple anymore to return just a string, which makes the API much more complex.

### PR DESCRIPTION
**Pull request by ndabAP**
## Demos

`yarn serve` and enter `loading`, `nano` or `klieh`.

## To Do

- [x] Command functions can return Vue.js Components
- [x] It is waited until `this.$_done()` is called
- [x] Hide cursor when command is running
- [x] Helper functions/components/computed variables
  - [x] `this.$_setIsFullscreen(isFullscreen: Boolean)` - to create commands like `nano`
  - [x] `this.$_executeCommand(command: string)` - to call subsequent commands
  - [x] `this.$_isRunning` - computed boolean property indicating status (`false` after calling `this.$_done()`)
- [x] Add documentation
- [x] Pass tests
- [x] Requires #80 to be merged first

Closes #5.

### CODE REVIEW

**Comment by ndabAP** [comment]
@krmax44 why did you remove `keepPrompt`?

**Comment by krmax44** [comment]
From what I could figure out of the code, changing it's value doesn't do anything. What am I missing?

**Comment by ndabAP** [comment]
> From what I could figure out of the code, changing it's value doesn't do anything. What am I missing?

@krmax44 it makes it possible to change prompt permanently for one STDIN. Example:

```bash
$ cd /home
/home$ whoami
/home$ you
```

**Comment by krmax44** [comment]
> > From what I could figure out of the code, changing it's value doesn't do anything. What am I missing?
> 
> @krmax44 it makes it possible to change prompt permanently for one STDIN. Example:
> 
> ```shell
> $ cd /home
> /home$ whoami
> /home$ you
> ```

That's a nifty feature! I feel like setting it via a prop feels a little strange though. What about allowing components to set subsequent prompts via `this.setPrompt(prompt: string)`?

**Comment by krmax44** [comment]
Can you give me push access to the `krmax44/feat/component-commands` branch, please?

**Comment by ndabAP** [comment]
@krmax44 oh sorry, should work now!

**Comment by krmax44** [comment]
@ndabAP tests passing now :tada:

**Comment by ndabAP** [comment]
>tests passing now

Oh my god, I played around with this hours today. Very good work!

**Comment by ndabAP** [comment]
@krmax44 there is an conceptional issue I just discovered. Before that, I can't publish.

When a component is returned and user already have a scroll bar visible, the application doesn't scroll when `STDOUT` comes in, see:

Screenshot from 2020-01-12 09-54-39

This pushes me a little back to the idea accepting a `Generator` function which may simulates the Unix signals in a better. The only work around for now seems to provide another function inside user given components which scrolls to bottom.

**Comment by krmax44** [comment]
@ndabAP We could use a Mutation Observer to track changes in height and scroll to the bottom when `Stdout` height changes.

**Comment by ndabAP** [comment]
@krmax44 I was only able to do it with `ResizeObserver`, see:

https://github.com/ndabAP/vue-command/pull/104/commits/db4b96a6c1fc04191f0167fffd2c0119f2b03c94

**Comment by krmax44** [comment]
Maybe we can make it so it only scrolls to bottom if it was at bottom before (so if you scrolled way up a small change wouldn't bring you down again).

**Comment by ndabAP** [comment]
@krmax44 I don't understand. Can you outline the single steps?

**Comment by krmax44** [comment]
Currently, it scrolls down whenever the stdout resizes. Now if you are scrolling up and the stdout resizes, it scrolls down again, blocking users to scroll up freely.

1. Check if the old height matches the old scrollbar position (check if it was scrolled all the way down).
2. If it matches, scroll down to the new height.

**Comment by ndabAP** [comment]
@krmax44 thanks for your input. Should work now.

**Comment by ndabAP** [comment]
Thanks for the fantastic work!

**Comment by krmax44** [comment]
Awesome, glad to help :)

**Comment by krmax44** [comment]
Shoot, I pushed b2619d1 a minute too late!

**Comment by ndabAP** [comment]
@krmax44 fixed it! Good catch.

**Pull request merged**
