### PR TITLE
Chore: Cut down the bundle size

### PR DESCRIPTION
**Pull request by krmax44**
[60+kb gzipped](https://bundlephobia.com/result?p=vue-command@7.0.5) seems to be quite a lot I think.
A couple of things come to mind when viewing the [bundle analyzer report](https://github.com/ndabAP/vue-command/files/3779774/report.zip):

- [x] Dropped Lodash and Ramda in favor of native ES6 functions
- [x] only ship required files in the package tarball e1b21f3
- [x] Polyfills can be disabled for libraries, see [CLI docs](https://cli.vuejs.org/guide/browser-compatibility.html#polyfills-when-building-as-library-or-web-components) - this was quite significant f4f2e93
- [ ] Yargs is quite big, but alternatives I found require specifying all options the parser will look for.

## Results

`vue-command.umd.min.js` is now only 14.2kB gzipped.

### CODE REVIEW

**Comment by ndabAP** [comment]
Nice, thanks a lot for that!

**Comment by ndabAP** [comment]
>Ramda seems to be unnecessary at times, maybe it can be removed completely

I agree. Ramda is something I'm playing personally around at the moment seeing if it helps the developer experience. But it can safely be dropped for this project.

>Lodash is fully embedded and not treeshaken for some reason

I love Lodash but it's also not totally necessary. It increases the readability like in this case:

```js
return flow([
  split(' '),
  head,
  current => when(
    () => isUndefined(find(keys(this.commands), command => eq(command, trim(current)))),
    constant(undefined)
  )(current)
])(this.current)
```

Still, maybe it's better build own helper functions. Another possibility would be to use dependencies explicitly, like [flow](https://www.npmjs.com/package/lodash.flow).

**Comment by krmax44** [comment]
> Another possibility would be to use dependencies explicitly, like flow .

I think that's probably the easiest choice.

**Comment by ndabAP** [comment]
> Yargs is quite big, but alternatives I found require specifying all options the parser will look for.

Will be tracked here: https://github.com/ndabAP/vue-command/issues/98.

**Pull request merged**
